@startuml
class CardZoom {
    - Awake() : void
    + OnMouseDown() : void
    + OnMouseUp() : void
}
MonoBehaviour <|-- CardZoom
CardZoom --> "canvas" GameObject
CardZoom --> "zoomCard" GameObject
@enduml
