@startuml
class ZoomCard {
    - isZoomed : bool = false
    - Start() : void
    + OnTap() : void
    - MoveCardCenter() : IEnumerator
    - MoveCardBack() : IEnumerator
}
MonoBehaviour <|-- ZoomCard
ZoomCard --> "originalPosition" Vector3
@enduml
